import { User, KnowledgeArticle, InsightPost, IssueTicket, OffboardingRecord, LearningPathway, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Bethel Haile',
    email: 'bethel.haile@a-mesob.et',
    role: 'junior',
    department: 'Customer Service',
    joinDate: '2025-03-15',
    avatar: 'BH',
    technicalSkills: [
      { name: 'Customer Service Fundamentals', completed: true, completedAt: '2025-04-10' },
      { name: 'Digital Signage Operations', completed: true, completedAt: '2025-04-25' },
      { name: 'Document Authentication', completed: false },
      { name: 'Conflict Resolution', completed: false },
    ],
    supervisorId: '2',
    bio: 'Passionate about delivering excellent public service to Ethiopian citizens.',
  },
  {
    id: '2',
    name: 'Daniel Kebede',
    email: 'daniel.kebede@a-mesob.et',
    role: 'senior',
    department: 'Operations',
    joinDate: '2023-08-01',
    avatar: 'DK',
    technicalSkills: [
      { name: 'Team Leadership', completed: true },
      { name: 'Process Optimization', completed: true },
      { name: 'Training & Mentorship', completed: true },
      { name: 'Incident Management', completed: true },
    ],
    bio: 'Operations specialist with 5+ years experience in government service delivery.',
  },
  {
    id: '3',
    name: 'Tigist Alemu',
    email: 'tigist.alemu@a-mesob.et',
    role: 'admin',
    department: 'HR',
    joinDate: '2022-01-10',
    avatar: 'TA',
    technicalSkills: [
      { name: 'HR Management', completed: true },
      { name: 'Knowledge Management', completed: true },
      { name: 'Offboarding Processes', completed: true },
      { name: 'Policy Development', completed: true },
    ],
    bio: 'HR Lead dedicated to preserving institutional knowledge and employee growth.',
  },
  {
    id: '4',
    name: 'Samuel Teshome',
    email: 'samuel.teshome@a-mesob.et',
    role: 'junior',
    department: 'IT',
    joinDate: '2025-01-20',
    avatar: 'ST',
    technicalSkills: [
      { name: 'System Administration', completed: true, completedAt: '2025-02-15' },
      { name: 'Network Troubleshooting', completed: false },
      { name: 'Security Protocols', completed: false },
    ],
    supervisorId: '5',
  },
  {
    id: '5',
    name: 'Frehiwot Worku',
    email: 'frehiwot.worku@a-mesob.et',
    role: 'senior',
    department: 'IT',
    joinDate: '2021-06-15',
    avatar: 'FW',
    technicalSkills: [
      { name: 'Infrastructure Management', completed: true },
      { name: 'Security Auditing', completed: true },
      { name: 'Vendor Management', completed: true },
    ],
    bio: 'IT Manager ensuring seamless digital operations for government services.',
  },
  {
    id: '6',
    name: 'Abebe Girma',
    email: 'abebe.girma@a-mesob.et',
    role: 'senior',
    department: 'Quality Assurance',
    joinDate: '2020-11-01',
    avatar: 'AG',
    technicalSkills: [
      { name: 'Quality Standards', completed: true },
      { name: 'Process Auditing', completed: true },
      { name: 'Performance Metrics', completed: true },
    ],
    bio: 'Quality assurance expert focused on citizen satisfaction metrics.',
  },
];

export const mockArticles: KnowledgeArticle[] = [
  {
    id: '1',
    title: 'Customer Service Escalation Procedures',
    content: `# Escalation Procedures\n\n## When to Escalate\n\nAlways escalate when:\n- Customer is dissatisfied after initial resolution attempt\n- Issue requires special authorization\n- Customer requests to speak with a supervisor\n- Problem affects multiple customers\n\n## Escalation Levels\n\n### Level 1: Team Lead\nFirst point of escalation for team-related issues.\n\n### Level 2: Department Manager  \nHandles cross-department conflicts.\n\n### Level 3: Operations Director\nComplex issues requiring resource allocation.\n\n## Documentation\nAll escalations must be logged in the Issue Tracking System within 15 minutes.`,
    category: 'Quality Guidelines',
    authorId: '2',
    tags: ['customer-service', 'escalation', 'procedures'],
    createdAt: '2025-03-15T10:30:00Z',
    updatedAt: '2025-04-20T14:22:00Z',
    views: 342,
    likes: 28,
    status: 'published',
  },
  {
    id: '2',
    title: 'New Business Registration - Step by Step Guide',
    content: `# New Business Registration Process\n\n## Prerequisites\n- TIN Number\n- Business Name Registration Certificate\n- Commercial Registration\n\n## Step 1: Document Verification\nVerify all submitted documents against original copies.\n\n## Step 2: System Entry\nEnter business details into the registration portal.\n\n## Step 3: Fee Collection\nCollect appropriate service fees.\n\n## Step 4: Processing Timeline\n- Normal: 3 business days\n- Express: Same day (with additional fee)`,
    category: 'Process Documentation',
    authorId: '6',
    tags: ['business', 'registration', 'step-by-step'],
    createdAt: '2025-02-10T09:00:00Z',
    updatedAt: '2025-04-18T11:45:00Z',
    views: 567,
    likes: 45,
    status: 'published',
  },
  {
    id: '3',
    title: 'IT Security Password Reset Protocol',
    content: `# Password Reset Procedures\n\n## For End Users\nUsers can reset passwords via the self-service portal using their registered email.\n\n## For Staff Assistance\nWhen a customer cannot reset independently:\n\n1. Verify identity with government-issued ID\n2. Document the request in the IT log\n3. Temporarily reset to a secure temporary password\n4. Instruct user to change upon next login\n\n## Security Reminders\n- Never share temporary passwords\n- Always verify caller/customer identity\n- Log all password reset requests`,
    category: 'IT Procedures',
    authorId: '5',
    tags: ['security', 'password', 'IT'],
    createdAt: '2025-01-25T08:00:00Z',
    updatedAt: '2025-04-15T16:30:00Z',
    views: 891,
    likes: 67,
    status: 'published',
  },
  {
    id: '4',
    title: 'Employee Leave Policy - 2025 Update',
    content: `# Leave Policy Guidelines\n\n## Annual Leave\n- 14 working days for first year\n- 21 working days after 3 years\n- 28 working days after 5 years\n\n## Sick Leave\n- Up to 30 days with medical certificate\n- Up to 7 days without certificate (annual limit: 14 days)\n\n## Maternity/Paternity Leave\n- Maternity: 90 calendar days paid\n- Paternity: 10 working days\n\n## Request Process\nSubmit leave requests through HR portal at least 5 days in advance.`,
    category: 'HR Policies',
    authorId: '3',
    tags: ['HR', 'leave', 'policy'],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-04-01T09:00:00Z',
    views: 1245,
    likes: 89,
    status: 'published',
  },
  {
    id: '5',
    title: 'Digital Service Integration Guidelines for Addis Ababa',
    content: `# Digital Service Integration Guidelines\n\n## Overview\nThis guide covers integration procedures for Addis Ababa metropolitan government services.\n\n## System Connectivity\nOur service center connects to:\n- Federal Ministry systems\n- Addis Ababa City Administration portal\n- Regional woreda offices\n\n## Common Integration Points\n1. TIN verification - Ministry of Revenue\n2. Business registration - Ministry of Trade\n3. Land documentation - Addis Ababa Land Bureau\n\n## Troubleshooting\nWhen integration fails, first check the central hub status before contacting individual departments.`,
    category: 'IT Procedures',
    authorId: '5',
    tags: ['digital-integration', 'addis-ababa', 'systems'],
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2025-04-10T14:00:00Z',
    views: 423,
    likes: 34,
    status: 'published',
  },
  {
    id: '6',
    title: 'Automated Reporting Tool Workarounds',
    content: `# Automated Reporting Tool - Known Issues & Solutions\n\n## Issue: Late Night Report Generation Fails\n**Symptom:** Reports scheduled after 10 PM do not generate.\n**Workaround:** Reschedule critical reports before 8 PM.\n\n## Issue: Amharic Character Rendering\n**Symptom:** Amharic characters appear as boxes in PDF exports.\n**Workaround:** Use the 'Legacy Export' option for Amharic content.\n\n## Issue: Multi-Branch Data Aggregation\n**Symptom:** Bole and Kazanchis branch data not combining correctly.\n**Workaround:** Run consolidation manually at 7 AM before peak hours.`,
    category: 'Process Documentation',
    authorId: '4',
    tags: ['automation', 'reporting', 'workarounds'],
    createdAt: '2025-02-15T11:00:00Z',
    updatedAt: '2025-04-05T09:30:00Z',
    views: 298,
    likes: 22,
    status: 'published',
  },
  {
    id: '7',
    title: 'Ethiopian Calendar Configuration Guide',
    content: `# Ethiopian Calendar (የኢትዮጵያ ቀን) Configuration\n\n## Why Ethiopian Calendar?\nMany government documents use the Ethiopian calendar (የግብጽ ቀነ-ሰማይ). Our systems must support both.\n\n## System Settings\n1. User preference: Settings > Regional > Calendar\n2. Default for new accounts: Ethiopian\n3. Display format: ET DD/MM/YYYY\n\n## Key Differences\n- Ethiopian year is 7-8 years behind Gregorian\n- 13 months of 30 days + 1 or 2 leap days\n- New Year (አበባ ጾም) typically around September 11`,
    category: 'IT Procedures',
    authorId: '4',
    tags: ['calendar', 'localization', 'amharic'],
    createdAt: '2025-01-10T14:00:00Z',
    updatedAt: '2025-03-20T10:00:00Z',
    views: 156,
    likes: 18,
    status: 'published',
  },
];

export const mockInsightPosts: InsightPost[] = [
  {
    id: '1',
    authorId: '2',
    title: 'Morning Rush Hour Strategy That Reduced Wait Times by 40%',
    content: 'We implemented a ticket-based queue system during peak hours (9-11 AM). Instead of first-come-first-served, we now prioritize by document complexity. Simple renewals go to express lane, complex registrations to standard lane. Results: Average wait dropped from 45 min to 27 min.',
    type: 'Insight',
    upvotes: 34,
    hasUpvoted: false,
    comments: [
      { id: 'c1', authorId: '3', content: 'Great initiative! Can you share the training materials used?', createdAt: '2025-04-20T10:00:00Z' },
      { id: 'c2', authorId: '1', content: 'This has helped me so much during my shifts!', createdAt: '2025-04-20T11:30:00Z' },
    ],
    createdAt: '2025-04-19T09:00:00Z',
  },
  {
    id: '2',
    authorId: '1',
    title: 'Challenge: Elderly Customers Struggling with Self-Service Kiosks',
    content: 'Many elderly citizens come in without family support and struggle with the digital kiosks. They often give up or take very long. I end up helping them manually which creates bottlenecks. Would appreciate any creative solutions or additional kiosk assistance protocols.',
    type: 'Challenge',
    upvotes: 28,
    hasUpvoted: false,
    comments: [
      { id: 'c3', authorId: '2', content: 'We are piloting a "digital assistant" program - senior employees can volunteer as kiosk guides during peak hours.', createdAt: '2025-04-21T08:00:00Z' },
      { id: 'c4', authorId: '6', content: 'Adding this to the next quality improvement meeting agenda.', createdAt: '2025-04-21T09:15:00Z' },
    ],
    createdAt: '2025-04-20T14:30:00Z',
  },
  {
    id: '3',
    authorId: '5',
    title: 'Lesson Learned: Always Verify Document Scanners Daily',
    content: 'We had a scanner malfunction go unnoticed for 2 days, resulting in 47 documents that needed rescanning. Now we have a mandatory daily scanner check at shift start. Takes 2 minutes, saves hours of rework.',
    type: 'Lesson Learned',
    upvotes: 41,
    hasUpvoted: false,
    comments: [],
    createdAt: '2025-04-18T16:00:00Z',
  },
  {
    id: '4',
    authorId: '6',
    title: 'Question: Standard Resolution Time for Quality Complaints?',
    content: 'What is our current SLA for quality-related complaints? I want to ensure our response times meet expectations and need to set proper customer expectations on first contact.',
    type: 'Question',
    upvotes: 12,
    hasUpvoted: false,
    comments: [
      { id: 'c5', authorId: '3', content: 'Standard is 48 hours for initial response, 5 business days for resolution. I can share the full policy document.', createdAt: '2025-04-22T10:00:00Z' },
    ],
    createdAt: '2025-04-21T11:00:00Z',
  },
];

export const mockIssueTickets: IssueTicket[] = [
  {
    id: '1',
    title: 'Authentication timeout errors during peak hours',
    description: 'Multiple customers experiencing session timeouts during 10-12 PM rush. Average timeout occurs after 5 minutes of inactivity.',
    status: 'Open',
    priority: 'High',
    category: 'IT',
    reportedById: '1',
    assignedToId: '5',
    createdAt: '2025-04-20T10:30:00Z',
    updatedAt: '2025-04-22T09:00:00Z',
  },
  {
    id: '2',
    title: 'Missing signature field on business registration form',
    description: 'The digital form V12.3 is missing the mandatory authorized signature field. Applications are being submitted incomplete.',
    status: 'In Progress',
    priority: 'Critical',
    category: 'Process',
    reportedById: '2',
    assignedToId: '4',
    createdAt: '2025-04-19T14:00:00Z',
    updatedAt: '2025-04-22T11:30:00Z',
  },
  {
    id: '3',
    title: 'Printer paper jam in Window 3',
    description: 'HP LaserJet at Window 3 has recurring paper jam issues. Technical team replaced rollers but problem persists.',
    status: 'Resolved',
    priority: 'Medium',
    category: 'Equipment',
    reportedById: '1',
    assignedToId: '5',
    resolutionNotes: 'Replaced entire printer unit. New unit working correctly for 2 weeks now.',
    createdAt: '2025-04-10T09:00:00Z',
    updatedAt: '2025-04-18T15:00:00Z',
  },
  {
    id: '4',
    title: 'Waiting area temperature too cold in mornings',
    description: 'Citizens complain about cold waiting area especially before 10 AM. AC thermostat seems to be set too low.',
    status: 'Open',
    priority: 'Low',
    category: 'Facilities',
    reportedById: '1',
    assignedToId: '6',
    createdAt: '2025-04-21T08:30:00Z',
    updatedAt: '2025-04-21T08:30:00Z',
  },
];

export const mockOffboardingRecords: OffboardingRecord[] = [
  {
    id: '1',
    employeeId: 'ex-1',
    employeeName: 'Meron Tadesse',
    department: 'Customer Service',
    lastWorkingDay: '2025-03-28',
    interviewDate: '2025-03-25',
    interviewerId: '3',
    unwrittenRules: 'Morning briefings set the tone for the day. Always check the whiteboard for daily targets. The senior staff takes lunch at 12:30 - try not to interrupt. Thursday afternoons are for cross-training.',
    institutionalKnowledge: 'The key to handling angry customers is to never match their energy. Use the calm-down phrase: "Let me help you resolve this." Most issues can be solved by checking the legacy system first - the new system sometimes lags.',
    keyContacts: [
      { name: 'Daniel Kebede', role: 'Operations Lead', email: 'daniel.kebede@a-mesob.et', notes: 'Go-to for all process questions' },
      { name: 'Girma Hailu', role: 'Legacy System Admin', email: 'girma.hailu@a-mesob.et', phone: '+251-911-XXX-XXXX', notes: 'Only person who knows the old database' },
    ],
    processMapUrl: '/processes/customer-service-workflow',
    knowledgeTransferStatus: 'completed',
    exitInterviewNotes: 'Meron was instrumental in onboarding 3 junior staff. Her notes on customer handling have been documented.',
    createdAt: '2025-03-25T10:00:00Z',
  },
  {
    id: '2',
    employeeId: 'ex-2',
    employeeName: 'Kibret Solomon',
    department: 'IT',
    lastWorkingDay: '2025-04-15',
    interviewDate: '2025-04-10',
    interviewerId: '3',
    unwrittenRules: 'System maintenance windows are Tuesday and Friday nights after 8 PM. Always announce downtime 24 hours in advance in the lobby and on the website. Never deploy on Fridays.',
    institutionalKnowledge: 'The backup system runs on custom scripts that Kibret wrote. Documentation exists but is incomplete. The vendor (EthioTech Solutions) relationship is managed by Frehiwot - new IT lead should shadow her first.',
    keyContacts: [
      { name: 'Frehiwot Worku', role: 'IT Manager', email: 'frehiwot.worku@a-mesob.et', notes: 'Primary vendor contact' },
      { name: 'Yonas Mesfin', role: 'EthioTech Support', email: 'support@ethiotech.et', phone: '+251-11-XXX-XXXX', notes: 'Vendor escalation' },
    ],
    knowledgeTransferStatus: 'in-progress',
    exitInterviewNotes: 'Exit interview scheduled for April 10. Knowledge transfer session scheduled for April 12.',
    createdAt: '2025-04-10T14:00:00Z',
  },
];

export const mockLearningPathways: LearningPathway[] = [
  {
    id: '1',
    title: 'Customer Service Excellence',
    description: 'Master the fundamentals of delivering exceptional government service to Ethiopian citizens.',
    category: 'Customer Service',
    modules: [
      { id: 'm1', title: 'Introduction to Public Service', description: 'Understanding our mission and values', duration: '1 hour', order: 1 },
      { id: 'm2', title: 'Citizen Interaction Basics', description: 'First impressions and communication skills', duration: '2 hours', order: 2 },
      { id: 'm3', title: 'Document Verification', description: 'Authenticating government documents', duration: '3 hours', order: 3 },
      { id: 'm4', title: 'Handling Difficult Situations', description: 'De-escalation and conflict resolution', duration: '2 hours', order: 4 },
      { id: 'm5', title: 'Digital System Navigation', description: 'Using our service delivery platforms', duration: '2 hours', order: 5 },
    ],
    requiredForRoles: ['junior'],
    progress: 'in-progress',
    enrolledAt: '2025-04-01',
  },
  {
    id: '2',
    title: 'IT Infrastructure Essentials',
    description: 'Learn to manage and troubleshoot our digital infrastructure.',
    category: 'IT',
    modules: [
      { id: 'm6', title: 'Network Fundamentals', description: 'Understanding our network architecture', duration: '3 hours', order: 1 },
      { id: 'm7', title: 'Security Protocols', description: 'Keeping citizen data safe', duration: '2 hours', order: 2 },
      { id: 'm8', title: 'Troubleshooting Basics', description: 'Common issues and solutions', duration: '4 hours', order: 3 },
    ],
    requiredForRoles: ['junior'],
    progress: 'not-started',
  },
  {
    id: '3',
    title: 'Team Leadership Fundamentals',
    description: 'Skills and knowledge for aspiring team leads and supervisors.',
    category: 'Leadership',
    modules: [
      { id: 'm9', title: 'Leadership Principles', description: 'Core leadership concepts for government services', duration: '2 hours', order: 1 },
      { id: 'm10', title: 'Performance Management', description: 'Evaluating and developing team members', duration: '3 hours', order: 2 },
      { id: 'm11', title: 'Conflict Resolution', description: 'Managing team dynamics', duration: '2 hours', order: 3 },
      { id: 'm12', title: 'Resource Allocation', description: 'Optimizing team productivity', duration: '2 hours', order: 4 },
    ],
    requiredForRoles: ['senior'],
    progress: 'completed',
    completedAt: '2025-03-15',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'info',
    title: 'New article published',
    message: 'Daniel published "Digital Service Integration Guidelines for Addis Ababa"',
    read: false,
    createdAt: '2025-04-22T09:00:00Z',
    link: '/knowledge-base',
  },
  {
    id: 'n2',
    type: 'warning',
    title: 'Issue requires attention',
    message: 'Authentication timeout errors ticket is still open',
    read: false,
    createdAt: '2025-04-22T08:00:00Z',
    link: '/issues',
  },
  {
    id: 'n3',
    type: 'mention',
    title: 'You were mentioned',
    message: 'Samuel mentioned you in "Elderly Customers" discussion',
    read: false,
    createdAt: '2025-04-21T14:30:00Z',
    link: '/community',
  },
  {
    id: 'n4',
    type: 'success',
    title: 'Learning milestone',
    message: 'You completed "Document Authentication" module',
    read: true,
    createdAt: '2025-04-20T16:00:00Z',
    link: '/learning',
  },
];
